/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package NewMallSlips;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.Date;
import java.util.Random;
import java.util.Scanner;
import javax.swing.Timer;
/**
 *
 * @author user
 */
public class NewMallSlip extends javax.swing.JFrame {
    
    double iTax = 7.5;
    /**
     * Creates new form NewMallSlip
     */
    public NewMallSlip() {
        initComponents();
        dt();
        times();
    }
    
    
    
    public void dt() {
    
      Date d = new Date();
      
      SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MMM-dd");
      
      String dd = sdf.format(d);
      jDate.setText(dd);
    
    }
    
    // Time
    Timer t;
    SimpleDateFormat st;
    
    public void times() {
    
       
        
      t = new Timer(0, new ActionListener() {

          @Override
          public void actionPerformed(ActionEvent e) {
              //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           
            Date dt = new Date(); 
            st = new SimpleDateFormat("hh:mm:ss a");
            
            String tt = st.format(dt);
            jTime1.setText(tt);
            
            }
        });
    
        t.start();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTime1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSubTotal5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jUnitPrice1 = new javax.swing.JTextField();
        jQty1 = new javax.swing.JTextField();
        jItem1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jItem2 = new javax.swing.JTextField();
        jQty2 = new javax.swing.JTextField();
        jUnitPrice2 = new javax.swing.JTextField();
        jSubTotal1 = new javax.swing.JTextField();
        jItem3 = new javax.swing.JTextField();
        jQty3 = new javax.swing.JTextField();
        jUnitPrice3 = new javax.swing.JTextField();
        jSubTotal2 = new javax.swing.JTextField();
        jItem4 = new javax.swing.JTextField();
        jQty4 = new javax.swing.JTextField();
        jUnitPrice4 = new javax.swing.JTextField();
        jSubTotal3 = new javax.swing.JTextField();
        jItem5 = new javax.swing.JTextField();
        jQty5 = new javax.swing.JTextField();
        jUnitPrice5 = new javax.swing.JTextField();
        jSubTotal4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTax = new javax.swing.JTextField();
        jNetPrice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnGenerateSlip = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtGenerateSlip = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(650, 800));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Date:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 24, -1, -1));

        jDate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jDate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDateActionPerformed(evt);
            }
        });
        jPanel1.add(jDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 22, 127, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Time:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 21, -1, 28));

        jTime1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTime1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 22, 127, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Item Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 85, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Item 1:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 127, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Item 2:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 174, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Item 3:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 223, -1, -1));

        jSubTotal5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubTotal5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSubTotal5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotal5ActionPerformed(evt);
            }
        });
        jPanel1.add(jSubTotal5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 84, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Qty");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 85, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Unit Price");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Sub Total");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Item Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 85, -1, -1));

        jUnitPrice1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUnitPrice1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jUnitPrice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnitPrice1ActionPerformed(evt);
            }
        });
        jPanel1.add(jUnitPrice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 126, 88, 30));

        jQty1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jQty1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty1ActionPerformed(evt);
            }
        });
        jPanel1.add(jQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 125, 31, -1));

        jItem1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem1ActionPerformed(evt);
            }
        });
        jPanel1.add(jItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 125, 102, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Item 4:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 275, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Item 5:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 324, -1, -1));

        jItem2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem2ActionPerformed(evt);
            }
        });
        jPanel1.add(jItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 172, 102, -1));

        jQty2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jQty2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty2ActionPerformed(evt);
            }
        });
        jPanel1.add(jQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 172, 31, -1));

        jUnitPrice2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUnitPrice2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jUnitPrice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnitPrice2ActionPerformed(evt);
            }
        });
        jPanel1.add(jUnitPrice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 88, -1));

        jSubTotal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubTotal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSubTotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotal1ActionPerformed(evt);
            }
        });
        jPanel1.add(jSubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 126, 84, 30));

        jItem3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jItem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem3ActionPerformed(evt);
            }
        });
        jPanel1.add(jItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 221, 102, -1));

        jQty3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jQty3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty3ActionPerformed(evt);
            }
        });
        jPanel1.add(jQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 221, 31, -1));

        jUnitPrice3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUnitPrice3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jUnitPrice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnitPrice3ActionPerformed(evt);
            }
        });
        jPanel1.add(jUnitPrice3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 88, -1));

        jSubTotal2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubTotal2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSubTotal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotal2ActionPerformed(evt);
            }
        });
        jPanel1.add(jSubTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 84, -1));

        jItem4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jItem4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem4ActionPerformed(evt);
            }
        });
        jPanel1.add(jItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 273, 102, -1));

        jQty4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jQty4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty4ActionPerformed(evt);
            }
        });
        jPanel1.add(jQty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 273, 31, -1));

        jUnitPrice4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUnitPrice4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jUnitPrice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnitPrice4ActionPerformed(evt);
            }
        });
        jPanel1.add(jUnitPrice4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 88, -1));

        jSubTotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubTotal3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSubTotal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotal3ActionPerformed(evt);
            }
        });
        jPanel1.add(jSubTotal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 84, -1));

        jItem5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jItem5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItem5ActionPerformed(evt);
            }
        });
        jPanel1.add(jItem5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 322, 102, -1));

        jQty5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jQty5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jQty5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQty5ActionPerformed(evt);
            }
        });
        jPanel1.add(jQty5, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 322, 31, -1));

        jUnitPrice5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jUnitPrice5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jUnitPrice5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnitPrice5ActionPerformed(evt);
            }
        });
        jPanel1.add(jUnitPrice5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 320, 88, -1));

        jSubTotal4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSubTotal4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jSubTotal4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubTotal4ActionPerformed(evt);
            }
        });
        jPanel1.add(jSubTotal4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 84, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Total");

        jTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTotalActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Tax");

        jTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTaxActionPerformed(evt);
            }
        });

        jNetPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jNetPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jNetPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNetPriceActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Net Price");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jTax)
                    .addComponent(jNetPrice))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jNetPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 240, 130));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Sum Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnPrintMouseClicked(evt);
            }
        });
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        jbtnGenerateSlip.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnGenerateSlip.setText("Generate Slip");
        jbtnGenerateSlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGenerateSlipActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGenerateSlip, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnResetMouseClicked(evt);
            }
        });
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 650, 530));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Emporium Supermarket Payment Slip");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtGenerateSlip.setColumns(20);
        jtxtGenerateSlip.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtxtGenerateSlip.setRows(5);
        jScrollPane1.setViewportView(jtxtGenerateSlip);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 500, 460));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Payment Print Out");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 230, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSubTotal5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotal5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubTotal5ActionPerformed

    private void jUnitPrice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitPrice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnitPrice1ActionPerformed

    private void jQty1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQty1ActionPerformed

    private void jItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem1ActionPerformed

    private void jItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem2ActionPerformed

    private void jQty2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQty2ActionPerformed

    private void jUnitPrice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitPrice2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnitPrice2ActionPerformed

    private void jSubTotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubTotal1ActionPerformed

    private void jItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem3ActionPerformed

    private void jQty3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQty3ActionPerformed

    private void jUnitPrice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitPrice3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnitPrice3ActionPerformed

    private void jSubTotal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubTotal2ActionPerformed

    private void jItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem4ActionPerformed

    private void jQty4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQty4ActionPerformed

    private void jUnitPrice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitPrice4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnitPrice4ActionPerformed

    private void jSubTotal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubTotal3ActionPerformed

    private void jItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jItem5ActionPerformed

    private void jQty5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQty5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jQty5ActionPerformed

    private void jUnitPrice5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnitPrice5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnitPrice5ActionPerformed

    private void jSubTotal4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubTotal4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSubTotal4ActionPerformed

    private void jTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTotalActionPerformed

    private void jTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTaxActionPerformed

    private void jNetPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNetPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jNetPriceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Exit JFrame:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        // TODO add your handling code here:
        
        try {
            jtxtGenerateSlip.print();
        } catch (Exception e) {
        
        
        }
        
        
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnGenerateSlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGenerateSlipActionPerformed
        // TODO add your handling code here:
        jtxtGenerateSlip.append("Emporium Payment Receipt Slip:\n" 
                    +   "**************************************\n"
                    + "\nDate:\t" + jDate.getText() +  "\t "+ jTime1.getText()
                    + "\nItem 1:\t" + jItem1.getText() +"\t "+ jQty1.getText() +"\t "+ jUnitPrice1.getText() +"\t "+ jSubTotal1.getText()
                    + "\nItem 2:\t" + jItem2.getText() +"\t "+ jQty2.getText() +"\t "+ jUnitPrice2.getText() +"\t "+ jSubTotal2.getText()
                    + "\nItem 3:\t" + jItem3.getText() +"\t "+ jQty3.getText() +"\t "+ jUnitPrice3.getText() +"\t "+ jSubTotal3.getText()
                    + "\nItem 4:\t" + jItem4.getText() +"\t "+ jQty4.getText() +"\t "+ jUnitPrice4.getText() +"\t "+ jSubTotal4.getText()
                    + "\nItem 5:\t" + jItem5.getText() +"\t "+ jQty5.getText() +"\t "+ jUnitPrice5.getText() +"\t "+ jSubTotal5.getText()
                    + "\nTotal:\t\t\t\t " + jTotal.getText() 
                    + "\nTax:\t\t\t\t " + jTax.getText() 
                    + "\nNetPrice:\t\t\t " + jNetPrice.getText()
        );
    }//GEN-LAST:event_jbtnGenerateSlipActionPerformed

    private void jbtnPrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnPrintMouseClicked
       
    }//GEN-LAST:event_jbtnPrintMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        double item1 = 31.4;
        double item2 = 29.5;
        double item3 = 18.9;
        double item4 = 20.7;
        double item5 = 12.5;
        
        
        double Qty1 = Double.parseDouble(jQty1.getText());
        double Qty2 = Double.parseDouble(jQty2.getText());
        double Qty3 = Double.parseDouble(jQty3.getText());
        double Qty4 = Double.parseDouble(jQty4.getText());
        double Qty5 = Double.parseDouble(jQty5.getText());
        
        
        double total, subTotal, Addup, vTax; 
        double purchase1, purchase2, purchase3, purchase4, purchase5;
        
        String jItem1 = String.format("$%.2f", item1);
        jUnitPrice1.setText(jItem1);
        
        String jItem2 = String.format("$%.2f", item2);
        jUnitPrice2.setText(jItem2);
        
        String jItem3 = String.format("$%.2f", item3);
        jUnitPrice3.setText(jItem3);
        
        String jItem4 = String.format("$%.2f", item4);
        jUnitPrice4.setText(jItem4);
        
        String jItem5 = String.format("$%.2f", item5);
        jUnitPrice5.setText(jItem5);
        
        
        purchase1 = Qty1 * item1;
        purchase2 = Qty2 * item2;
        purchase3 = Qty3 * item3;
        purchase4 = Qty4 * item4;
        purchase5 = Qty5 * item5;
        
        String sub1 = String.format("$%.2f", purchase1);
        jSubTotal1.setText(sub1);
        
        String sub2 = String.format("$%.2f", purchase2);
        jSubTotal2.setText(sub2);
        
        String sub3 = String.format("$%.2f", purchase3);
        jSubTotal3.setText(sub3);
        
        String sub4 = String.format("$%.2f", purchase4);
        jSubTotal4.setText(sub4);
        
        String sub5 = String.format("$%.2f", purchase5);
        jSubTotal5.setText(sub5);
        
        subTotal = purchase1 + purchase2 + purchase3 + purchase4 + purchase5;
        
        
          //====================Tax ===========================
        
        vTax = (subTotal * iTax)/100;
        
        String subTotalAll = String.format("$%.2f", subTotal);
        jTotal.setText(subTotalAll);
        
        //====================Date and Time====================
        
//        Calendar timer = Calendar.getInstance();
//        Time ti = Time.valueOf(LocalTime.MIN);
//        
//        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
//        jDate.setText(tTime.format(ti.getTime()));
//        
//        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MMM-yyyy");
//        jDate.setText(Tdate.format(timer.getTime()));
        
        //====================Total Price====================
        
        String subTax = String.format("$%.2f", vTax);
        jTax.setText(subTax);
        
        //====================Net Price======================
        
        Addup = subTotal + vTax;
        
        String TotalAll = String.format("$%.2f", Addup);
        jNetPrice.setText(TotalAll);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDateActionPerformed

    private void jbtnResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnResetMouseClicked
        // TODO add your handling code here:
         // Reset all fields:
        jItem1.setText(null);
        jItem2.setText(null);
        jItem3.setText(null);
        jItem4.setText(null);
        jItem5.setText(null);
        
        jQty1.setText(null);
        jQty2.setText(null);
        jQty3.setText(null);
        jQty4.setText(null);
        jQty5.setText(null);
        
        jUnitPrice1.setText(null);
        jUnitPrice2.setText(null);
        jUnitPrice3.setText(null);
        jUnitPrice4.setText(null);
        jUnitPrice5.setText(null);
        
        jSubTotal1.setText(null);
        jSubTotal2.setText(null);
        jSubTotal3.setText(null);
        jSubTotal4.setText(null);
        jSubTotal5.setText(null);
        
        jTotal.setText(null);
        jTax.setText(null);
        jNetPrice.setText(null);
        jDate.setText(null);
        jTime1.setText(null);
        jtxtGenerateSlip.setText(null);
    }//GEN-LAST:event_jbtnResetMouseClicked

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMallSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMallSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMallSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMallSlip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMallSlip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jDate;
    private javax.swing.JTextField jItem1;
    private javax.swing.JTextField jItem2;
    private javax.swing.JTextField jItem3;
    private javax.swing.JTextField jItem4;
    private javax.swing.JTextField jItem5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNetPrice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jQty1;
    private javax.swing.JTextField jQty2;
    private javax.swing.JTextField jQty3;
    private javax.swing.JTextField jQty4;
    private javax.swing.JTextField jQty5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jSubTotal1;
    private javax.swing.JTextField jSubTotal2;
    private javax.swing.JTextField jSubTotal3;
    private javax.swing.JTextField jSubTotal4;
    private javax.swing.JTextField jSubTotal5;
    private javax.swing.JTextField jTax;
    private javax.swing.JTextField jTime1;
    private javax.swing.JTextField jTotal;
    private javax.swing.JTextField jUnitPrice1;
    private javax.swing.JTextField jUnitPrice2;
    private javax.swing.JTextField jUnitPrice3;
    private javax.swing.JTextField jUnitPrice4;
    private javax.swing.JTextField jUnitPrice5;
    private javax.swing.JButton jbtnGenerateSlip;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextArea jtxtGenerateSlip;
    // End of variables declaration//GEN-END:variables
}
